### ISSUE TITLE
not able to login on hostel manager and admin login plz help me..

### ISSUE THREAD

**Issue by a1d9** [Bharat-Reddy/Hostel-Management-System#13]

**Comment by bhatt098** [comment]
facing same issue dude

**Comment by Nithya155** [comment]
canyoupls tell admin details

**Comment by 1css** [comment]
Not able to login on hostel management

**Comment by Atharva3101** [comment]
go to PhpMyAdmin. create a hostel manager in the "hostel manager" table and put password as "$2y$10$xF8VfInXP5fDyAIRwYtM5eisgtJD0YlNfw4CdNXZ7jmdTy0EZHYfy".
This is the encryption for "12345"

**Comment by rahuldas2097** [comment]
Can you tell me the user name?

**Comment by Atharva3101** [comment]
I think you can put whatever you want . Or just admin
