### ISSUE TITLE
Not able to login on hostel management 

### ISSUE THREAD

**Issue by 1css** [Bharat-Reddy/Hostel-Management-System#16]
Not able to login on hostel management

**Comment by Atharva3101** [comment]
go to PhpMyAdmin. create a hostel manager in the "hostel manager" table and put password as "$2y$10$xF8VfInXP5fDyAIRwYtM5eisgtJD0YlNfw4CdNXZ7jmdTy0EZHYfy".
This is the encryption for "12345"
