### ISSUE TITLE
can't setup!!!!!

### ISSUE THREAD

**Issue by Priyeshp27** [Bharat-Reddy/Hostel-Management-System#21]
HOW TO SETUP DATABASE? please help me out of this as I'm new to PHP & XAMPP.

**Comment by IAMLEIIKUN** [comment]
you can message me

> HOW TO SETUP DATABASE? please help me out of this as I'm new to PHP & XAMPP.

**Comment by Nikhil7028** [comment]
> you can message me
> 
> > HOW TO SETUP DATABASE? please help me out of this as I'm new to PHP & XAMPP.

to setup the database run some sql quiries which is given in the database folder.
