### ISSUE TITLE
Reflected XSS in Application form

### ISSUE THREAD

**Issue by anupshaw50** [Bharat-Reddy/Hostel-Management-System#4]
Found Reflected XSS 

Url : http://IP/hms/application_form.php?id=%22%3E%3Cscript%3Ealert(1)%3C/script%3E%3C

Vulnerable Code : 	
```			
94 : <form action="application_form.php?id=<?php echo $_GET['id']?>" method="post">
104 : <input type="text" name="hostel" placeholder="Hostel" value="<?php echo $_GET['id']?>" required="" disabled="disabled">
```
Mitigation : Don't use variable directly, Filter it

**Comment by straightdot** [comment]
Hello please give me 100$ bounty, this is my first report and I have to pay exam fees. Please help!!
