### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by alv300** [Bharat-Reddy/Hostel-Management-System#6]
i'm adding the user and password in the hostel manager db but when it comes to login in it shows an error;http://localhost/Hostel-Management-System-master/login-hostel_manager.php?error=wrongpwd  please help

**Comment by Bharat-Reddy** [comment]
Just check the conditions which lead to wrong password in the code. I've written the code in such a way that even if the uname is wrong I'll redirect you to the login page with message wrong password.

**Comment by ayush-0605** [comment]
@alv300 have you got the admin login details?
If so,please help!!!

**Comment by BrianKhosa** [comment]
Hi Bharat, did you manage to post the admin credentials? I just want to see how the admin panel looks like. thanks
